declare const NAME: string, KAFKA_ADDRESS: string, INPUT_TOPIC: string, OUTPUT_TOPIC: string, DBPEDIA_SPARQL_ENDPOINT: string;
export { NAME, KAFKA_ADDRESS, INPUT_TOPIC, OUTPUT_TOPIC, DBPEDIA_SPARQL_ENDPOINT, };
